name: "Magister Exporter"
version: "0.0.21"
slug: magister_exporter
arch:
  - aarch64
  - amd64
host_network: true
description: "Description here"
options:
  credentials: []
  days_to_fetch: 14
schema:
  credentials:
    - name: str
      username: str
      password: str
  days_to_fetch: int
ports:
  15060/tcp: 15060